wip: travis: install hwdata explicitly
k8snetworkplumbingwg/sriov-network-device-plugin pull request #313
Opened 2021-01-18 03:37 UTC by zshi-redhat

2021-01-18 06:54 UTC, adrianchiris commented
ghw may depend on other files later on,
a more robust approach would be to create an interface (and mock) for ghw/pcidb libs and use dependency injection for them.
then in tests it would not depend on the filesystem.

This can be a future improvement ofc.

2021-01-19 01:53 UTC, zshi-redhat commented
/cc @martinkennelly @adrianchiris updated PR, ready to merge.

2021-01-19 11:26 UTC, adrianchiris requested changes
Thanks for working on it Zenghui !

More context in commit message on why this change is needed for posterity is appreciated

2021-01-19 11:26 UTC, adrianchiris commented on .travis.yml
> +  - sudo apt-get install hwdata -y
nit: similar to the above apt-get update command, id use -q flag as then apt-get output is more suitable for logging

i.e replace `-y` with `-yq`

```
-q, --quiet
Quiet. Produces output suitable for logging, omitting progress indicators. More q's will produce more quiet up to a maximum of two. You can also use -q=# to set the quiet level, overriding the configuration file. Note that quiet level 2 implies -y, you should never use -qq without a no-action modifier such as -d, --print-uris or -s as APT may decided to do something you did not expect.
```

2021-01-21 01:30 UTC, zshi-redhat commented
> Thanks for working on it Zenghui !
> 
> More context in commit message on why this change is needed for posterity is appreciated

added.

2021-01-21 07:54 UTC, adrianchiris commented
golang:alpine was updated yesterday

https://hub.docker.com/layers/golang/library/golang/alpine/images/sha256-e1b06b72500a80383af2a426db0e29d7b65211b297ffd47a0939266cded3fd6a?context=explore

This causes ddp tool to fail linking.

2021-01-21 10:33 UTC, zshi-redhat commented
> golang:alpine was updated yesterday
> 
> https://hub.docker.com/layers/golang/library/golang/alpine/images/sha256-e1b06b72500a80383af2a426db0e29d7b65211b297ffd47a0939266cded3fd6a?context=explore
> 
> This causes ddp tool to fail linking during make image in travis.
> 
> option 1: look into possible fix to ddp tool to work with the installed toolchain in the newer image
> option 2: explicitly specify tag for an older base container image (then look into option 1)

option 2.

Is it an option to update `images/ddptool-1.0.0.0.tar.gz`?

2021-01-21 14:36 UTC, martinkennelly commented
I am looking into resolving this DDPTool build error with Alpine 3.13. I think sticking with a previous alpine build version is desired until then to unblock us.

I am also seeing an issue with Alpine 3.13 internally here in Intel behind proxies and we see the same error that started off this PR during building of DP. The alpine community are fixing it.

2021-01-22 12:39 UTC, martinkennelly approved these changes

2021-01-22 12:40 UTC, martinkennelly commented
/retest

2021-01-22 12:40 UTC, zshi-redhat commented
Rebased and include fix for another CI failure: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/317

2021-01-22 14:41 UTC, merged